# Generated by Django 3.2.9 on 2022-03-19 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_registration_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='true_or_false',
        ),
    ]
