# Generated by Django 3.2.9 on 2022-03-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220319_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='answer',
            new_name='answers',
        ),
        migrations.AlterField(
            model_name='registration',
            name='answer',
            field=models.ManyToManyField(blank=True, to='main.Answers'),
        ),
    ]
